---
- name: Clone homelab-infra repo
  ansible.builtin.git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ dotfiles_repo_dest }}"
    update: true
    recursive: true
    accept_newhostkey: false
  tags: [dotfiles]

- name: Run dotbot install to create symlinks
  ansible.builtin.command:
    cmd: ./install
    chdir: "{{ dotfiles_repo_dest }}/dotfiles"
  register: dotbot_output
  changed_when: "'All tasks executed successfully' in dotbot_output.stdout"
  tags: [dotfiles]

- name: Display dotbot output
  ansible.builtin.debug:
    var: dotbot_output.stdout_lines
  tags: [dotfiles]
