---
git_ssh_key_name: "id_ed25519"
git_ssh_generate_key: false
git_ssh_hosts:
  - host: github.com
    hostname: github.com
    user: git
    key_name: "{{ git_ssh_key_name }}"
    identities_only: true
git_known_hosts:
  - name: github.com
    key: "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"
