---
dotfiles_home: "{{ ansible_facts.user_dir }}"
dotfiles_repo_root: "{{ dotfiles_home }}/repos/homelab-infra"
dotfiles_source: "{{ playbook_dir }}/../../dotfiles/"
dotfiles_dest: "{{ dotfiles_repo_root }}/dotfiles"
